version: '3.9'
services:
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
  app:
    build: .
    environment:
      - PORT=8080
      - RATE_LIMIT_MODE=auto
      - RATE_LIMIT_RPS=2
      - RATE_LIMIT_BLOCK_SECONDS=10
      - RATE_LIMIT_TOKEN_HEADER=API_KEY
      - REDIS_ADDR=redis:6379
      - REDIS_DB=0
      - REDIS_PASSWORD=
      # Example overrides
      - RATE_LIMIT_TOKEN_OVERRIDES=abc123:5:10
    ports:
      - "8080:8080"
    depends_on:
      - redis


