version: '3.8'

services:
  weather-cep-service:
    build: .
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      - WEATHER_API_KEY=sua_chave_aqui
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
